apiVersion: certmanager.io/v1
kind: Certificate
metadata:
  name: jeebediop-com-tls
spec:
  secretName: jeebediop-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jeebediop-com
  dnsNames:
    - jeebediop.com
    - www.jeebediop.com
